


import {NAVIGATOR_STATUS,
TASK_TYPE,
UserNavigatorStatus,
NavigatorJourney,
NavigatorStageGroup,
NavigatorStage,
NavigatorTask,
EiSelectOption,
EiFieldLoaderConfig,
QuestionnaireTaskConfig,
QuizTaskConfig,
QuestionnaireQuestion,
ContentTaskConfig,
CONTENT_SUB_TYPES,
ContentTaskPageConfig,
Frame,
External,
Trivia } from './navigator';

export const navTypes = [
NAVIGATOR_STATUS,
TASK_TYPE,
UserNavigatorStatus,
NavigatorJourney,
NavigatorStageGroup,
NavigatorStage,
NavigatorTask,
EiSelectOption,
EiFieldLoaderConfig,
QuestionnaireTaskConfig,
QuizTaskConfig,
QuestionnaireQuestion,
ContentTaskConfig,
CONTENT_SUB_TYPES,
ContentTaskPageConfig,
Frame,
External,
Trivia,
];
